### PR TITLE
Erd

### PR DESCRIPTION
**Pull request by AbdelrhmanAmin**
I've drawn the diagram requested for the user, friendship, post, comment, like relationships

### CODE REVIEW

**Review by enaburekhan — COMMENTED** [review]
# Status: Invalid
Hi Abdo!
This project is hereby marked as invalid. Kindly resubmit another code review request since you have closed this PR before been review. 

You can reach me on slack @Eric Enaburekhan if you have any questions.
Happy coding!!!
Eric Enaburekhan

**Review by ghost — CHANGES_REQUESTED** [review]
# Status: Changes Required 🛑 

## Hello team 👋,

**Great job on this milestone 👏. However, there are a few requirements needed.**

1). **The user table should have an image_link/avatar column.**
2). **In the friendship table, an integer is not an attribute. Change the word integer to status. Also, status is not a key, replace status with word key. In the post table, text is not an attribute. Change it to body/content. Also, body is not a key. Change body to the word key or leave it blank. Do the same for the comments table.**

3). **The line endpoints describing the relationship between the user table and friendship table are not well defined.**

4). **Set up the linter checks for your pull request.**

## Happy coding 🥂.

**PS: You can reach me on slack (Rose Wanjohi).**

**Comment by arslanbisharat** [comment]
> # Status: Changes Required 🛑
> ## Hello team 👋,
> **Great job on this milestone 👏. However, there are a few requirements needed.**
> 
> 1). **The user table should have an image_link/avatar column.**
> 2). **In the friendship table, an integer is not an attribute. Change the word integer to status. Also, status is not a key, replace status with word key. In the post table, text is not an attribute. Change it to body/content. Also, body is not a key. Change body to the word key or leave it blank. Do the same for the comments table.**
> 3). **The line endpoints describing the relationship between the user table and friendship table are not well defined.**
> 
> 4). **Set up the linter checks for your pull request.**
> 
> ## Happy coding 🥂.
> **PS: You can reach me on slack (Rose Wanjohi).**

Please work on these changes and request another review.

**Comment by AbdelrhmanAmin** [comment]
@arslanbisharat Did you look at the docs??!
https://github.com/AbdelrhmanAmin/ror-social-media/blob/ERD/docs/Screenshot%20from%202021-01-22%2002-38-16.png

**Review by ghost — APPROVED** [review]
# Status: Approved 🎉 

**Congratulations team 👏, and good luck with your next milestone 😃.**

**Pull request merged**
